name: Elixir Quality Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: 
      - '*'

permissions:
  contents: read
  
jobs:
  build:

    name: Build and test
    runs-on: ubuntu-20.04
    env:
      otp: 25.1.0
      elixir: 1.14.0

    steps:
    - uses: actions/checkout@v3
    - name: Install OTP and Elixir
      uses: erlef/setup-beam@v1
      with:
          otp-version: ${{ env.otp }}
          elixir-version: ${{ env.elixir }}
          build-app: false

    - name: Check code formatting
      run: mix format --check-formatted
      if: always()
      
    - name: Run Credo (static code analysis tool) focus on teaching and code consistency. 
      run: mix credo suggest --min-priority=normal
      if: always()
      
    - name: Prints cross reference information between modules.
      run: mix xref graph --label compile-connected --fail-above 0
      if: always()
      
    - name: Check for security vulnerabilities in Phoenix project
      run: mix sobelow -i Config.HTTPS
      if: always()
